# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6380eb917f315d21b14572b29631ca687066c505b0f8cd6ce77d9501cf525cd7aaafff42012bf4eb61fd6d0fe96839795e5360a797c3ced3c414eb955bdd38a3

test:
  secret_key_base: 0e41925b045d2eb4d7a957b0ec9c1b74ae29190c4635b12494046ae870e9fbd6d696cd7133834bdb0f3dfa841d959b5ff2eb05b5132618bd8625e0f76cd29b44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
